[package]
name = "rusty_ip"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.14", features = ["json", "blocking"] }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
cli-clipboard = "=0.4.0"